

 export var product=[{id:1,brand:'samsung',price:1500,categeory:'electronics',pname:"mobile",rating:"3",photo:"./imgs/s1.jpg"},
 {id:2,brand:'samsung',price:2000,categeory:'electronics',pname:"mobile",rating:"4",photo:"./imgs/s2.jpg"},
 {id:3,brand:'samsung',price:2500,categeory:'electronics',pname:"mobile",rating:"5",photo:"./imgs/s3.jpg"},
 {id:4,brand:'samsung',price:3000,categeory:'electronics',pname:"mobile",rating:"4",photo:"./imgs/s4.jpg"},
 {id:5,brand:'samsung',price:3500,categeory:'electronics',pname:"mobile",rating:"7",photo:"./imgs/s5.jpg"},
 {id:6,brand:'samsung',price:4000,categeory:'electronics',pname:"mobile",rating:"8",photo:"./imgs/s6.jpg"},
 {id:7,brand:'samsung',price:4500,categeory:'electronics',pname:"mobile",rating:"4",photo:"./imgs/s7.jpg"},
 {id:8,brand:'samsung',price:5000,categeory:'electronics',pname:"mobile",rating:"3",photo:"./imgs/s8.jpg"},
 {id:9,brand:'samsung',price:5500,categeory:'electronics',pname:"mobile",rating:"9",photo:"./imgs/s9.jpg"},
 {id:10,brand:'samsung',price:6000,categeory:'electronics',pname:"mobile",rating:"8",photo:"./imgs/s10.jpg"},
 
 {id:11,brand:'samsung',price:1500,categeory:'electronics',pname:"watch",rating:"5",photo:"./imgs/sw1.jpg"},
 {id:12,brand:'samsung',price:2000,categeory:'electronics',pname:"watch",rating:"6",photo:"./imgs/sw2.jpg"},
 {id:13,brand:'samsung',price:2500,categeory:'electronics',pname:"watch",rating:"3",photo:"./imgs/sw3.jpg"},
 {id:14,brand:'samsung',price:3000,categeory:'electronics',pname:"watch",rating:"5",photo:"./imgs/sw4.jpg"},
 {id:15,brand:'samsung',price:3500,categeory:'electronics',pname:"watch",rating:"6",photo:"./imgs/sw5.jpg"},
 {id:16,brand:'samsung',price:4000,categeory:'electronics',pname:"watch",rating:"8",photo:"./imgs/sw6.jpg"},
 {id:17,brand:'samsung',price:4500,categeory:'electronics',pname:"watch",rating:"8",photo:"./imgs/sw7.jpg"},
 {id:18,brand:'samsung',price:5000,categeory:'electronics',pname:"watch",rating:"9",photo:"./imgs/sw8.jpg"},
 {id:19,brand:'samsung',price:5500,categeory:'electronics',pname:"watch",rating:"4",photo:"./imgs/sw9.jpg"},
 {id:20,brand:'samsung',price:6000,categeory:'electronics',pname:"watch",rating:"9",photo:"./imgs/sw10.jpg"},
 
 {id:21,brand:'samsung',price:1500,categeory:'electronics',pname:"laptop",rating:"3",photo:"./imgs/sl1.jpg"},
 {id:22,brand:'samsung',price:2000,categeory:'electronics',pname:"watch",rating:"4",photo:"./imgs/sl2.jpg"},
 {id:23,brand:'samsung',price:2500,categeory:'electronics',pname:"watch",rating:"5",photo:"./imgs/sl3.jpg"},
 {id:24,brand:'samsung',price:3000,categeory:'electronics',pname:"watch",rating:"7",photo:"./imgs/sl4.jpg"},
 {id:25,brand:'samsung',price:3500,categeory:'electronics',pname:"watch",rating:"9",photo:"./imgs/sl5.jpg"},
 {id:26,brand:'samsung',price:4000,categeory:'electronics',pname:"watch",rating:"6",photo:"./imgs/sl6.jpg"},
 {id:27,brand:'samsung',price:4500,categeory:'electronics',pname:"watch",rating:"7",photo:"./imgs/sl7.jpg"},
 {id:28,brand:'samsung',price:5000,categeory:'electronics',pname:"watch",rating:"8",photo:"./imgs/sl8.jpg"},
 {id:29,brand:'samsung',price:5500,categeory:'electronics',pname:"watch",rating:"9",photo:"./imgs/sl9.jpg"},
 {id:30,brand:'samsung',price:6000,categeory:'electronics',pname:"watch",rating:"7",photo:"./imgs/sl10.jpg"},
 
 {id:31,brand:'samsung',price:1500,categeory:'electronics',pname:"fridge",rating:"3",photo:"./imgs/sf1.jpg"},
 {id:32,brand:'samsung',price:2000,categeory:'electronics',pname:"fridge",rating:"6",photo:"./imgs/sf2.jpg"},
 {id:33,brand:'samsung',price:2500,categeory:'electronics',pname:"fridge",rating:"4",photo:"./imgs/sf3.jpg"},
 {id:34,brand:'samsung',price:3000,categeory:'electronics',pname:"fridge",rating:"4",photo:"./imgs/sf4.jpg"},
 {id:35,brand:'samsung',price:3500,categeory:'electronics',pname:"fridge",rating:"7",photo:"./imgs/sf5.jpg"},
 {id:36,brand:'samsung',price:4000,categeory:'electronics',pname:"fridge",rating:"5",photo:"./imgs/sf6.jpg"},
 {id:37,brand:'samsung',price:4500,categeory:'electronics',pname:"fridge",rating:"8",photo:"./imgs/sf7.jpg"},
 {id:38,brand:'samsung',price:5000,categeory:'electronics',pname:"fridge",rating:"9",photo:"./imgs/sf8.jpg"},
 {id:39,brand:'samsung',price:5500,categeory:'electronics',pname:"fridge",rating:"8",photo:"./imgs/sf9.jpg"},
 {id:40,brand:'samsung',price:6000,categeory:'electronics',pname:"fridge",rating:"5",photo:"./imgs/sf10.jpg"},
 
 {id:41,brand:'samsung',price:1500,categeory:'electronics',rating:"3",photo:"./imgs/st1.jpg"},
 {id:42,brand:'samsung',price:2000,categeory:'electronics',rating:"2",photo:"./imgs/st2.jpg"},
 {id:43,brand:'samsung',price:2500,categeory:'electronics',rating:"4",photo:"./imgs/st3.jpg"},
 {id:44,brand:'samsung',price:3000,categeory:'electronics',rating:"5",photo:"./imgs/st4.jpg"},
 {id:45,brand:'samsung',price:3500,categeory:'electronics',rating:"6",photo:"./imgs/st5.jpg"},
 {id:46,brand:'samsung',price:4000,categeory:'electronics',rating:"7",photo:"./imgs/st6.jpg"},
 {id:47,brand:'samsung',price:4500,categeory:'electronics',rating:"8",photo:"./imgs/st7.jpg"},
 {id:48,brand:'samsung',price:5000,categeory:'electronics',rating:"9",photo:"./imgs/st8.jpg"},
 {id:49,brand:'samsung',price:5500,categeory:'electronics',rating:"1",photo:"./imgs/st9.jpg"},
 {id:50,brand:'samsung',price:6000,categeory:'electronics',rating:"2",photo:"./imgs/st10.jpg"},
 // samsung products completed
 
 {id:51,brand:'lg',price:1500,categeory:'electronics',pname:"mobile",rating:"3",photo:"./imgs/lm1.jpg"},
 {id:52,brand:'lg',price:2000,categeory:'electronics',pname:"mobile",rating:"4",photo:"./imgs/lm2.jpg"},
 {id:53,brand:'lg',price:2500,categeory:'electronics',pname:"mobile",rating:"5",photo:"./imgs/lm3.jpg"},
 {id:54,brand:'lg',price:3000,categeory:'electronics',pname:"mobile",rating:"4",photo:"./imgs/lm4.jpg"},
 {id:55,brand:'lg',price:3500,categeory:'electronics',pname:"mobile",rating:"7",photo:"./imgs/lm5.jpg"},
 {id:56,brand:'lg',price:4000,categeory:'electronics',pname:"mobile",rating:"8",photo:"./imgs/lm6.jpg"},
 {id:57,brand:'lg',price:4500,categeory:'electronics',pname:"mobile",rating:"4",photo:"./imgs/lm7.jpg"},
 {id:58,brand:'lg',price:5000,categeory:'electronics',pname:"mobile",rating:"3",photo:"./imgs/lm8.jpg"},
 {id:59,brand:'lg',price:5500,categeory:'electronics',pname:"mobile",rating:"9",photo:"./imgs/lm9.jpg"},
 {id:60,brand:'lg',price:6000,categeory:'electronics',pname:"mobile",rating:"8",photo:"./imgs/lm10.jpg"},
 
 {id:61,brand:'lg',price:1500,categeory:'electronics',rating:"3",photo:"./imgs/lt1.jpg"},
 {id:62,brand:'lg',price:2000,categeory:'electronics',rating:"4",photo:"./imgs/lt2.jpg"},
 {id:63,brand:'lg',price:2500,categeory:'electronics',rating:"5",photo:"./imgs/lt3.jpg"},
 {id:64,brand:'lg',price:3000,categeory:'electronics',rating:"4",photo:"./imgs/lt4.jpg"},
 {id:65,brand:'lg',price:3500,categeory:'electronics',rating:"7",photo:"./imgs/lt5.jpg"},
 {id:66,brand:'lg',price:4000,categeory:'electronics',rating:"8",photo:"./imgs/lt6.jpg"},
 {id:67,brand:'lg',price:4500,categeory:'electronics',rating:"4",photo:"./imgs/lt7.jpg"},
 {id:68,brand:'lg',price:5000,categeory:'electronics',rating:"3",photo:"./imgs/lt8.jpg"},
 {id:69,brand:'lg',price:5500,categeory:'electronics',rating:"9",photo:"./imgs/lt9.jpg"},
 {id:70,brand:'lg',price:6000,categeory:'electronics',rating:"8",photo:"./imgs/lt10.jpg"},
 
 {id:71,brand:'lg',price:1500,categeory:'electronics',rating:"3",photo:"./imgs/lf1.jpg"},
 {id:72,brand:'lg',price:2000,categeory:'electronics',rating:"4",photo:"./imgs/lf2.jpg"},
 {id:73,brand:'lg',price:2500,categeory:'electronics',rating:"5",photo:"./imgs/lf3.jpg"},
 {id:74,brand:'lg',price:3000,categeory:'electronics',rating:"4",photo:"./imgs/lf4.jpg"},
 {id:75,brand:'lg',price:3500,categeory:'electronics',rating:"7",photo:"./images/lf5.jpg"},
 {id:76,brand:'lg',price:4000,categeory:'electronics',rating:"8",photo:"./imgs/lf6.jpg"},
 {id:77,brand:'lg',price:4500,categeory:'electronics',rating:"4",photo:"./imgs/lf7.jpg"},
 {id:78,brand:'lg',price:5000,categeory:'electronics',rating:"3",photo:"./imgs/lf8.jpg"},
 {id:79,brand:'lg',price:5500,categeory:'electronics',rating:"9",photo:"./imgs/lf9.jpg"},
 {id:80,brand:'lg',price:6000,categeory:'electronics',rating:"8",photo:"./imgs/lf10.jpg"},
 
 
 // lg products end here
 {id:101,brand:'nike',price:1500,categeory:'fashion',rating:"3",photo:"./imgs/nc1.jpg"},
 {id:102,brand:'nike',price:2000,categeory:'fashion',rating:"4",photo:"./imgs/nc2.jpg"},
 {id:103,brand:'nike',price:2500,categeory:'fashion',rating:"5",photo:"./imgs/nc3.jpg"},
 {id:104,brand:'nike',price:3000,categeory:'fashion',rating:"6",photo:"./imgs/nc4.jpg"},
 {id:105,brand:'nike',price:3500,categeory:'fashion',rating:"7",photo:"./imgs/nc5.jpg"},
 {id:106,brand:'nike',price:4000,categeory:'fashion',rating:"8",photo:"./imgs/nc6.jpg"},
 {id:107,brand:'nike',price:4500,categeory:'fashion',rating:"1",photo:"./imgs/nc7.jpg"},
 {id:108,brand:'nike',price:5000,categeory:'fashion',rating:"2",photo:"./imgs/nc8.jpg"},
 {id:109,brand:'nike',price:5500,categeory:'fashion',rating:"9",photo:"./imgs/nc9.jpg"},
 {id:110,brand:'nike',price:6000,categeory:'fashion',rating:"8",photo:"./imgs/nc10.jpg"},
 
 {id:111,brand:'nike',price:1500,categeory:'cloths',rating:"3",photo:"./imgs/nt1.jpg"},
 {id:112,brand:'nike',price:2000,categeory:'cloths',rating:"4",photo:"./imgs/nt2.jpg"},
 {id:113,brand:'nike',price:2500,categeory:'cloths',rating:"5",photo:"./imgs/nt3.jpg"},
 {id:114,brand:'nike',price:3000,categeory:'cloths',rating:"6",photo:"./imgs/nt4.jpg"},
 {id:115,brand:'nike',price:3500,categeory:'cloths',rating:"7",photo:"./imgs/nt5.jpg"},
 {id:116,brand:'nike',price:4000,categeory:'cloths',rating:"8",photo:"./imgs/nt6.jpg"},
 {id:117,brand:'nike',price:4500,categeory:'cloths',rating:"1",photo:"./imgs/nt7.jpg"},
 {id:118,brand:'nike',price:5000,categeory:'cloths',rating:"2",photo:"./imgs/nt8.jpg"},
 {id:119,brand:'nike',price:5500,categeory:'cloths',rating:"9",photo:"./imgs/nt9.jpg"},
 {id:120,brand:'nike',price:6000,categeory:'cloths',rating:"8",photo:"./imgs/nt10.jpg"},
 
 {id:121,brand:'nike',price:1500,categeory:'cloths',rating:"3",photo:"./imgs/nd1.jpg"},
 {id:122,brand:'nike',price:2000,categeory:'cloths',rating:"4",photo:"./imgs/nd2.jpg"},
 {id:123,brand:'nike',price:2500,categeory:'cloths',rating:"5",photo:"./imgs/nd3.jpg"},
 {id:124,brand:'nike',price:3000,categeory:'cloths',rating:"6",photo:"./imgs/nd4.jpg"},
 {id:125,brand:'nike',price:3500,categeory:'cloths',rating:"7",photo:"./imgs/nd5.jpg"},
 {id:126,brand:'nike',price:4000,categeory:'cloths',rating:"8",photo:"./imgs/nd6.jpg"},
 {id:127,brand:'nike',price:4500,categeory:'cloths',rating:"1",photo:"./imgs/nd7.jpg"},
 {id:128,brand:'nike',price:5000,categeory:'cloths',rating:"2",photo:"./imgs/nd8.jpg"},
 {id:129,brand:'nike',price:5500,categeory:'cloths',rating:"9",photo:"./imgs/nd9.jpg"},
 {id:130,brand:'nike',price:6000,categeory:'cloths',rating:"8",photo:"./imgs/nd10.jpg"},
 
 {id:131,brand:'nike',price:1500,categeory:'footwear',rating:"3",photo:"./imgs/ns1.jpg"},
 {id:132,brand:'nike',price:2000,categeory:'footwear',rating:"4",photo:"./imgs/ns2.jpg"},
 {id:133,brand:'nike',price:2500,categeory:'footwear',rating:"5",photo:"./imgs/ns3.jpg"},
 {id:134,brand:'nike',price:3000,categeory:'footwear',rating:"6",photo:"./imgs/ns4.jpg"},
 {id:135,brand:'nike',price:3500,categeory:'footwear',rating:"7",photo:"./imgs/ns5.jpg"},
 {id:136,brand:'nike',price:4000,categeory:'footwear',rating:"8",photo:"./imgs/ns6.jpg"},
 {id:137,brand:'nike',price:4500,categeory:'footwear',rating:"1",photo:"./imgs/ns7.jpg"},
 {id:138,brand:'nike',price:5000,categeory:'footwear',rating:"2",photo:"./imgs/ns8.jpg"},
 {id:139,brand:'nike',price:5500,categeory:'footwear',rating:"9",photo:"./imgs/ns9.jpg"},
 {id:140,brand:'nike',price:6000,categeory:'footwear',rating:"8",photo:"./imgs/ns10.jpg"},
 
 {id:141,brand:'nike',price:1500,categeory:'fashion',rating:"3",photo:"./imgs/nb1.jpg"},
 {id:142,brand:'nike',price:2000,categeory:'fashion',rating:"4",photo:"./imgs/nb2.jpg"},
 {id:143,brand:'nike',price:2500,categeory:'fashion',rating:"5",photo:"./imgs/nb3.jpg"},
 {id:144,brand:'nike',price:3000,categeory:'fashion',rating:"6",photo:"./imgs/nb4.jpg"},
 {id:145,brand:'nike',price:3500,categeory:'fashion',rating:"7",photo:"./imgs/nb5.jpg"},
 {id:146,brand:'nike',price:4000,categeory:'fashion',rating:"8",photo:"./imgs/nb6.jpg"},
 {id:147,brand:'nike',price:4500,categeory:'fashion',rating:"1",photo:"./imgs/nb7.jpg"},
 {id:148,brand:'nike',price:5000,categeory:'fashion',rating:"2",photo:"./imgs/nb8.jpg"},
 {id:149,brand:'nike',price:5500,categeory:'fashion',rating:"9",photo:"./imgs/nb9.jpg"},
 {id:150,brand:'nike',price:6000,categeory:'fashion',rating:"8",photo:"./imgs/nb10.jpg"},
 
 // niki products end here
 
 {id:151,brand:'puma',price:1500,categeory:'fashion',rating:"3",photo:"./imgs/pc1.jpg"},
 {id:152,brand:'puma',price:2000,categeory:'fashion',rating:"4",photo:"./imgs/pc2.jpg"},
 {id:153,brand:'puma',price:2500,categeory:'fashion',rating:"5",photo:"./imgs/pc3.jpg"},
 {id:154,brand:'puma',price:3000,categeory:'fashion',rating:"6",photo:"./imgs/pc4.jpg"},
 {id:155,brand:'puma',price:3500,categeory:'fashion',rating:"7",photo:"./imgs/pc5.jpg"},
 {id:156,brand:'puma',price:4000,categeory:'fashion',rating:"8",photo:"./imgs/pc6.jpg"},
 {id:157,brand:'puma',price:4500,categeory:'fashion',rating:"1",photo:"./imgs/pc7.jpg"},
 {id:158,brand:'puma',price:5000,categeory:'fashion',rating:"2",photo:"./imgs/pc8.jpg"},
 {id:159,brand:'puma',price:5500,categeory:'fashion',rating:"9",photo:"./imgs/pc9.jpg"},
 {id:160,brand:'puma',price:6000,categeory:'fashion',rating:"8",photo:"./imgs/pc10.jpg"},
 
 
 {id:161,brand:'puma',price:1500,categeory:'cloths',rating:"3",photo:"./imgs/pt1.jpg"},
 {id:162,brand:'puma',price:2000,categeory:'cloths',rating:"4",photo:"./imgs/pt2.jpg"},
 {id:163,brand:'puma',price:2500,categeory:'cloths',rating:"5",photo:"./imgs/pt3.jpg"},
 {id:164,brand:'puma',price:3000,categeory:'cloths',rating:"6",photo:"./imgs/pt4.jpg"},
 {id:165,brand:'puma',price:3500,categeory:'cloths',rating:"7",photo:"./imgs/pt5.jpg"},
 {id:166,brand:'puma',price:4000,categeory:'cloths',rating:"8",photo:"./imgs/pt6.jpg"},
 {id:167,brand:'puma',price:4500,categeory:'cloths',rating:"1",photo:"./imgs/pt7.jpg"},
 {id:168,brand:'puma',price:5000,categeory:'cloths',rating:"2",photo:"./imgs/pt8.jpg"},
 {id:169,brand:'puma',price:5500,categeory:'cloths',rating:"9",photo:"./imgs/pt9.png"},
 {id:170,brand:'puma',price:6000,categeory:'cloths',rating:"8",photo:"./imgs/pt10.jpg"},
 
 {id:171,brand:'puma',price:1500,categeory:'cloths',rating:"3",photo:"./imgs/pd1.jpg"},
 {id:172,brand:'puma',price:2000,categeory:'cloths',rating:"4",photo:"./imgs/pd2.jpg"},
 {id:173,brand:'puma',price:2500,categeory:'cloths',rating:"5",photo:"./imgs/pd3.jpg"},
 {id:174,brand:'puma',price:3000,categeory:'cloths',rating:"6",photo:"./imgs/pd4.jpg"},
 {id:175,brand:'puma',price:3500,categeory:'cloths',rating:"7",photo:"./imgs/pd5.jpg"},
 {id:176,brand:'puma',price:4000,categeory:'cloths',rating:"8",photo:"./imgs/pd6.jpg"},
 {id:177,brand:'puma',price:4500,categeory:'cloths',rating:"1",photo:"./imgs/pd7.jpg"},
 {id:178,brand:'puma',price:5000,categeory:'cloths',rating:"2",photo:"./imgs/pd8.jpg"},
 {id:179,brand:'puma',price:5500,categeory:'cloths',rating:"9",photo:"./imgs/pd9.jpg"},
 {id:180,brand:'puma',price:6000,categeory:'cloths',rating:"8",photo:"./imgs/pd10.jpg"},
 
 {id:181,brand:'puma',price:1500,categeory:'footwear',rating:"3",photo:"./imgs/ps1.jpg"},
 {id:182,brand:'puma',price:2000,categeory:'footwear',rating:"4",photo:"./imgs/ps2.jpg"},
 {id:183,brand:'puma',price:2500,categeory:'footwear',rating:"5",photo:"./imgs/ps3.jpg"},
 {id:184,brand:'puma',price:3000,categeory:'footwear',rating:"6",photo:"./imgs/ps4.jpg"},
 {id:185,brand:'puma',price:3500,categeory:'footwear',rating:"7",photo:"./imgs/ps5.jpg"},
 {id:186,brand:'puma',price:4000,categeory:'footwear',rating:"8",photo:"./imgs/ps6.jpg"},
 {id:187,brand:'puma',price:4500,categeory:'footwear',rating:"1",photo:"./imgs/ps7.jpg"},
 {id:188,brand:'puma',price:5000,categeory:'footwear',rating:"2",photo:"./imgs/ps8.jpg"},
 {id:189,brand:'puma',price:5500,categeory:'footwear',rating:"9",photo:"./imgs/ps9.jpg"},
 {id:190,brand:'puma',price:6000,categeory:'footwear',rating:"8",photo:"./imgs/ps10.jpg"},
 
 {id:191,brand:'puma',price:1500,categeory:'fashion',rating:"3",photo:"./imgs/pb1.jpg"},
 {id:192,brand:'puma',price:2000,categeory:'fashion',rating:"4",photo:"./imgs/pb2.jpg"},
 {id:193,brand:'puma',price:2500,categeory:'fashion',rating:"5",photo:"./imgs/pb3.jpg"},
 {id:194,brand:'puma',price:3000,categeory:'fashion',rating:"6",photo:"./imgs/pb4.jpg"},
 {id:195,brand:'puma',price:3500,categeory:'fashion',rating:"7",photo:"./imgs/pb5.jpg"},
 {id:196,brand:'puma',price:4000,categeory:'fashion',rating:"8",photo:"./imgs/pb6.jpg"},
 {id:197,brand:'puma',price:4500,categeory:'fashion',rating:"1",photo:"./imgs/pb7.jpg"},
 {id:198,brand:'puma',price:5000,categeory:'fashion',rating:"2",photo:"./imgs/pb8.jpg"},
 {id:199,brand:'puma',price:5500,categeory:'fashion',rating:"9",photo:"./imgs/pb9.jpg"},
 {id:200,brand:'puma',price:6000,categeory:'fashion',rating:"8",photo:"./imgs/pb10.jpg"},
 ]


